### ISSUE TITLE
Craft 4 support?

### ISSUE THREAD

**Issue by janhenckens** [Rias500/craft-width-fieldtype#11]
Hey, do you have any plans for a version that works with Craft 4?
Happy to make a PR for it if you would consider that.

**Comment by DynamiteGoesBoom** [comment]
@janhenckens  you should be able to find it on the plug-in store. We’re already using it on other projects already.

**Comment by DynamiteGoesBoom** [comment]
This has been tagged and released.

**Comment by janhenckens** [comment]
Thanks @DynamiteGoesBoom!
