### ISSUE TITLE
[Enhancement] Add more width options

### ISSUE THREAD

**Issue by mikestecker** [Rias500/craft-width-fieldtype#2]
Could you add some more width options or the ability to custom define them? I would love to use with [Tailwind](https://tailwindcss.com) which has a lot of [width options](https://tailwindcss.com/docs/width).

**Comment by riasvdv** [comment]
We added these basic ones for a client project but one of the first things I'll implement is more options!

**Comment by riasvdv** [comment]
I've added all the default Tailwind options to the new release!

<img width="440" alt="afbeelding" src="https://user-images.githubusercontent.com/3626559/36282241-d0729e54-12a0-11e8-9a5d-368110e10bff.png">
