### ISSUE TITLE
1/1 field icon not visible

### ISSUE THREAD

**Issue by lukeyouell** [Rias500/craft-width-fieldtype#5]
<img width="642" alt="image" src="https://user-images.githubusercontent.com/24975058/37087023-02f25176-21f1-11e8-8193-e224307cf64d.png">

Craft 3.0.0-RC14

**Comment by riasvdv** [comment]
I'm not seeing this, could you inspect element and see what image it tries to get?

**Comment by lukeyouell** [comment]
@Rias500 it attempts to load `/cpresources/2627d73c/6f3da569/Full.svg` but the image cannot be found.

The plugin icon doesn't load in the plugins section either:
<img width="330" alt="image" src="https://user-images.githubusercontent.com/24975058/37100245-57075c74-221a-11e8-942d-cae879b4c66f.png">

**Comment by ockam** [comment]
@Rias500 

That’s because of casing: Linux is case sensitive and the url point to `Full.svg`while the image on disk is `full.svg`.

In Width_input.twig, you should add the `lower` filter. Or use `1-1.svg` instead.

**Comment by lukeyouell** [comment]
@ockam @Rias500 I can confirm this as the icon is being displayed correctly in the field settings, the file being called there is `full.svg`, not `Full.svg`

**Comment by riasvdv** [comment]
Thanks for the PR @lukeyouell, new version tagged with the fix :)
