### ISSUE TITLE
Selected value is too weakly distinguished

### ISSUE THREAD

**Issue by michel-o** [Rias500/craft-width-fieldtype#7]
I like this plugin very much, there is just one issue with UX.

Selected value is too weakly distinguished - just faint shadow. I propose some other distinction, for example border.

**Comment by riasvdv** [comment]
I've made the icons a bit smaller in 1.0.6, which makes it clearer which button is pressed.

Before:
![afbeelding](https://user-images.githubusercontent.com/3626559/43406944-9d7eecce-941d-11e8-9bda-06f90335427d.png)

After:
![afbeelding](https://user-images.githubusercontent.com/3626559/43406951-a43dcc56-941d-11e8-8533-1e0d4e0ddb40.png)
