### ISSUE TITLE
Width field will not save under craft 3.7.31

### ISSUE THREAD

**Issue by anchovy** [Rias500/craft-width-fieldtype#9]
We've got a width field being used in a supertable; it was obviously added fine at some point but now we can't make any changes to the superfield because the width field is throwing an error?

**System:**
PHP version: 8.0.8
MySQL: 8.0.27
Craft Pro: 3.7.31
Yii version: 2.0.44
Twig version: v2.14.11
Guzzle version: 7.4.1
Width Fieldtype: v1.0.7
Super Table: v2.7.1
Field Manager:v 2.2.4

The snaps below show this in action - if we change the field to a text field, or any other field (snap 4 and 5), the changes are saved as expected. 

If I try and add a new width field via the field-manager plugin I get the following error (snap 6):
`{"success":false,"error":{"options":["Invalid value for $options[{key}].","Invalid value for $options[{key}].","Invalid value for $options[{key}].","Invalid value for $options[{key}].","Invalid value for $options[{key}].","Invalid value for $options[{key}].","Invalid value for $options[{key}].","Invalid value for $options[{key}].","Invalid value for $options[{key}].","Invalid value for $options[{key}]."]}}`

![1-make-a-change-to-field](https://user-images.githubusercontent.com/599005/153501556-afc9f9f4-026e-439d-ac3c-90df1f63ed6e.png)

![2-will-not-save](https://user-images.githubusercontent.com/599005/153501604-b2d03dd6-2d89-40a1-91e8-93df7e4296bf.png)

![3-error-indicated-but-no-error-shown](https://user-images.githubusercontent.com/599005/153501627-3cd58897-cee6-460d-a8c1-322d6ceae378.png)

![4-change-to-text](https://user-images.githubusercontent.com/599005/153501644-22b4ef44-c072-4fca-8f8d-3e615f952258.png)

![5-change-to-text-saved](https://user-images.githubusercontent.com/599005/153501658-122f28f3-3db3-4055-87ed-61d172b196b8.png)

![6-error-message](https://user-images.githubusercontent.com/599005/153502457-4f280a26-8377-4a0d-a925-a51764f0b3b8.png)

Thanks in advance.

**Comment by DynamiteGoesBoom** [comment]
@anchovy Thanks for bringing this to our attention. It's likely due to a recent SuperTable update and we'll take a look as soon as we can 👍

**Comment by anchovy** [comment]
@DynamiteGoesBoom Great - thanks. A similar issue occurs when adding as a plain old field, so think it might be due to a craft update.

**Comment by michtio** [comment]
@anchovy 

I pushed up a fix and did a release, could you confirm the field saves again as it is supposed to? I think somewhere in Craft, they moved from saving / parsing values instead of an integer as a string.

**Comment by anchovy** [comment]
Hi @michtio Sorry - missed that DM for some reason. That's fix did the trick and we can save fields again now - thanks!

**Comment by michtio** [comment]
Thank you for confirming @anchovy !
